server:
  port: 8080

spring:
  datasource:
    # MySQL?????????3306?????ai_chat_db
    url: 
    username:    # SQLyog????
    password:   # SQLyog????
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL8??
llm:
  api_url: 
  api_key: 
  model: 